name: token-limiter-concurrent
version: 0.1.0.0
github: "NorfairKing/token-limiter-concurrent"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2022-2024 Tom Sydney Kerckhove"
synopsis: "A thread-safe concurrent token-bucket rate limiter that guarantees fairness"

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  token-limiter-concurrent-test:
    main: Spec.hs
    build-tools: sydtest-discover
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - async
    - genvalidity
    - genvalidity-sydtest
    - stm
    - sydtest
    - token-limiter-concurrent
