name: "Test Nix Flake"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  nix:
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest
        # - macos-latest
    name: Nix on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-stable

    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - if: false  # runs out of space building things.
      name: "Check `nix develop` shell"
      run: nix develop --check

    - run: nix build

    - continue-on-error: false
      run: nix flake check
